name = "PeakSEO"
client_id = "3c495798894eca0ab3e388afa424ac32"
application_url = "https://peakseo.onkra.online"
embedded = true


[access_scopes]
scopes = "write_products,read_products,write_files,read_files"

[auth]
redirect_urls = [
  "https://peakseo.onkra.online/auth/callback",
  "https://peakseo.onkra.online/auth/shopify/callback",
  "https://peakseo.onkra.online/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]
uri = "https://peakseo.onkra.online/webhooks"

[app_proxy]
url = "https://peakseo.onkra.online/api/proxy"
subpath = "store-pickup"
prefix = "apps"

[pos]
embedded = false

[app_preferences]
url = "https://peakseo.onkra.online/preferences"

[build]
automatically_update_urls_on_dev = false
